# docker-compose.yml

version: '3.8'
services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:///development.db
      - JWT_SECRET_KEY=your_secret_key_here
