#!/usr/bin/python3
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from app import db

class Country(db.Model):
    """
    Country class representing a country and its cities

    Attributes:
        id (int): Unique identifier for each country (automatically generated by SQLAlchemy).
        name (str): Name of the country.
        cities (list): List of cities in the country.
    """
    __tablename__ = 'countries'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128), nullable=False)

    def __init__(self, name):
        """
        Initialize a new Country instance

        Args:
            name (str): The name of the country.
        """
        self.name = name
        self.cities = []

    def add_city(self, city):
        """
        Add a city to the country's list of cities

        Args:
            city (City): The city to be added.
        """
        self.cities.append(city)

    def __repr__(self):
        """
        Return a string representation of the Country instance.
        """
        return f'<Country {self.name}>'
